// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZU3zps5koi5J2W-1qEgkiskgDLnPMpEY',
    appId: '1:954571161833:web:e03c992bdcf5d465177078',
    messagingSenderId: '954571161833',
    projectId: 'countryapp-cb26f',
    authDomain: 'countryapp-cb26f.firebaseapp.com',
    storageBucket: 'countryapp-cb26f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiJKrn2W7Mhee2AT4WqGEf2u6mPrD0VDk',
    appId: '1:954571161833:android:0873dcc0c1a3c3ec177078',
    messagingSenderId: '954571161833',
    projectId: 'countryapp-cb26f',
    storageBucket: 'countryapp-cb26f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARz9S-OIRhifqy-qkTKJy1eheC-_vT_wE',
    appId: '1:954571161833:ios:a2cfcc6f29b58f6e177078',
    messagingSenderId: '954571161833',
    projectId: 'countryapp-cb26f',
    storageBucket: 'countryapp-cb26f.firebasestorage.app',
    iosBundleId: 'com.example.taskcountryapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARz9S-OIRhifqy-qkTKJy1eheC-_vT_wE',
    appId: '1:954571161833:ios:a2cfcc6f29b58f6e177078',
    messagingSenderId: '954571161833',
    projectId: 'countryapp-cb26f',
    storageBucket: 'countryapp-cb26f.firebasestorage.app',
    iosBundleId: 'com.example.taskcountryapp',
  );
}
